### ISSUE TITLE
It doesn't work with alfred 3

### ISSUE THREAD

**Issue by ctwhome** [clarencecastillo/alfred-powerthesaurus#5]
Hi! is it possible that the new release doesn't work with Alfred 3?
![image](https://user-images.githubusercontent.com/4195550/70633528-ff923000-1c30-11ea-959b-efb55827e6e5.png)

thanks!

**Comment by ctwhome** [comment]
I have the las v3 version: 3.8.5

**Comment by ctwhome** [comment]
hallo?? is there someone in the other side?

**Comment by vitorgalvao** [comment]
You need to use Alfred 4 for the latest version of the Workflow. It no longer works with version 3.

**Comment by clarencecastillo** [comment]
Unfortunately, I don't use Alfred 3 anymore so I couldn't test it on that version. I've updated the release sites to only show support for Alfred 4 so there will be no confusion. Thanks for the heads up!

**Comment by vitorgalvao** [comment]
> I don't use Alfred 3 anymore so I couldn't test it on that version.

It’s not even a case of testing. When you save a Workflow in a version of Alfred, previous major versions will no longer be able to open it (a Workflow saved in v3 does not open in v2 as well).

The only way to keep this working on v3 would be to keep it around and always edit it in that version, meaning you could never take advantage of Alfred’s new features.

For something that you’re distributing for free, presumably out of your free time, that’s not worth it. You’d only be giving yourself extra work for something you wouldn’t even be able to take advantage of.

**Comment by clarencecastillo** [comment]
> When you save a Workflow in a version of Alfred, previous major versions will no longer be able to open it (a Workflow saved in v3 does not open in v2 as well).

Oh wow, I haven't really looked it up and didn't know this was a thing. Kinda makes sense for Alfred devs to do it this way since opting for backwards compatibility will probably impose some level of limitation on how much of the new features we can use in later versions.

Seems [there is a way](https://www.alfredforum.com/topic/13041-i-created-the-workflow-in-alfred4-and-exported-it/) to do it in parallel, but you're exactly right, it wouldn't really make sense for me to work on it given my capacity and what I can gain from it.

That said, the project is open for contributions, in case anyone wants to work on it 😉
